export interface SupportedLanguage {
  code: string;
  label: string;
}

export const languages: SupportedLanguage[] = [
  { code: "en", label: "English" },
  { code: "az", label: "Azerbaijani" },
  { code: "tr", label: "Turkish" },
  { code: "ru", label: "Russian" },
  { code: "de", label: "German" },
  { code: "fr", label: "French" },
  { code: "es", label: "Spanish" },
  { code: "it", label: "Italian" },
  { code: "pt", label: "Portuguese" },
  { code: "ar", label: "Arabic" },
  { code: "zh", label: "Chinese (Simplified)" },
  { code: "zh-TW", label: "Chinese (Traditional)" },
  { code: "ja", label: "Japanese" },
  { code: "ko", label: "Korean" },
  { code: "fa", label: "Persian" },
  { code: "hi", label: "Hindi" },
  { code: "bn", label: "Bengali" },
  { code: "pl", label: "Polish" },
  { code: "uk", label: "Ukrainian" },
  { code: "nl", label: "Dutch" },
  { code: "cs", label: "Czech" },
  { code: "sv", label: "Swedish" },
  { code: "fi", label: "Finnish" },
  { code: "no", label: "Norwegian" },
  { code: "da", label: "Danish" },
  { code: "el", label: "Greek" },
  { code: "ro", label: "Romanian" },
  { code: "hu", label: "Hungarian" },
  { code: "id", label: "Indonesian" },
  { code: "vi", label: "Vietnamese" },
  { code: "th", label: "Thai" },
  { code: "sr", label: "Serbian" },
  { code: "sk", label: "Slovak" },
  { code: "sl", label: "Slovenian" },
  { code: "bg", label: "Bulgarian" },
  { code: "hr", label: "Croatian" },
  { code: "he", label: "Hebrew" },
  { code: "et", label: "Estonian" },
  { code: "lt", label: "Lithuanian" },
  { code: "lv", label: "Latvian" },
  { code: "sq", label: "Albanian" },
  { code: "ms", label: "Malay" },
  { code: "fil", label: "Filipino" },
  { code: "ta", label: "Tamil" },
  { code: "ur", label: "Urdu" },
  { code: "sw", label: "Swahili" },
  { code: "ka", label: "Georgian" },
  { code: "hy", label: "Armenian" },
  { code: "kk", label: "Kazakh" },
  { code: "uz", label: "Uzbek" },
  { code: "mn", label: "Mongolian" },
  { code: "ps", label: "Pashto" },
  { code: "af", label: "Afrikaans" },
  { code: "zu", label: "Zulu" },
  { code: "xh", label: "Xhosa" },
  { code: "yo", label: "Yoruba" },
  { code: "am", label: "Amharic" },
  { code: "ne", label: "Nepali" },
  { code: "my", label: "Burmese" },
  { code: "si", label: "Sinhala" },
  { code: "te", label: "Telugu" },
  { code: "ml", label: "Malayalam" },
  { code: "gu", label: "Gujarati" },
  { code: "mr", label: "Marathi" },
  { code: "kn", label: "Kannada" },
  { code: "pa", label: "Punjabi" },
  { code: "eu", label: "Basque" },
  { code: "gl", label: "Galician" },
  { code: "ca", label: "Catalan" },
  { code: "eo", label: "Esperanto" }
];

export const defaultLanguage = "en";
